### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by matthieudolci** [rismoney/puppet-baremetal-windows#8]
Hello,

We are really interested into your project and are trying to make it work to deploy VMs via foreman and wds on xenserver.
Could you explain a little more how to use this project?

Thank you!

**Comment by rismoney** [comment]
This goes into how I use it - 
https://github.com/rismoney/puppet-baremetal-windows/issues/7

I would be more than happy to answer any questions you have.

**Comment by rismoney** [comment]
The end result of this repo, is a customized boot wim that includes a working version of puppet within the Windows PE environment.  

If this sounds like something you want - i could work on some better docs.
